# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "D:\\server_files", "/local_file", type: "rsync"
  config.vm.disk :disk, name: "data", size: "60GB"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
#    vb.memory = 15360
#    vb.cpus = 8
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "sudo su -" >> .bashrc
  SHELL
end